spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.application.name=twitter-api-project-c38-onl
server.servlet.context-path=/api/v1
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
